#!/usr/bin/env python3
"""Published per-case truth for the committed public fixtures ("golden vectors").

  uv run python scripts/golden_truth.py            # check the files and print what they hold

The files under ``protocol/golden_truth/`` hold the agreed truth (``state`` and ``defects``,
the two fields the scorer reads) of every committed PUBLIC fixture capsule whose truth is
otherwise computed by a reference executor that is not published. Each case is bound to its
capsule by the capsule's evidence commitment (``canonical.evidence_commitment``), recomputed
here from the capsule content and never read from the capsule's own field. A capsule that is
not in a file has no published truth: ``GoldenTruth.truth_for`` raises, it never guesses.

What the files are not: they hold no hidden instance, no reference executor code and no rule
of how truth is derived. They cover fixtures generated by the public generators at fixed,
published identifiers and seeds, whose truth the public-contract baseline already reproduces.

Each file carries ``set_digest``, the SHA-256 of its canonical JSON without that field, so an
edit that is not also re-sealed is detected. The seal is tamper evidence for the file, not proof
of the truth: the proof that this truth is the one the validator used is that the scorer,
fed with it, reproduces the attested validator digest (``scripts/verify_attestation.py``).

This module imports only the public canonical helpers. It runs in the private tree and in the
public tree unchanged.
"""

from __future__ import annotations

import copy
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GOLDEN_DIR = ROOT / "protocol" / "golden_truth"
SCHEMA = "sn87-golden-truth/0.1"
DIGEST_FIELD = "set_digest"
STATES = ("FINDINGS", "NO_MATERIAL_DEVIATION", "INSUFFICIENT_EVIDENCE_ABSTAIN")
SEVERITIES = ("LOW", "MEDIUM", "HIGH")

from sn87_provenonce.canonical import canonical_bytes, evidence_commitment  # noqa: E402


class GoldenTruthMissing(LookupError):
    """No published truth for this capsule (or no golden files at all)."""


class GoldenTruthInvalid(ValueError):
    """A golden file is malformed, tampered with, or contradicts another file."""


def seal(document: dict[str, Any]) -> str:
    """``set_digest`` of a document: SHA-256 of its canonical JSON without the digest field."""
    body = {k: v for k, v in document.items() if k != DIGEST_FIELD}
    return "sha256:" + hashlib.sha256(canonical_bytes(body)).hexdigest()


def _check_truth(where: str, truth: Any) -> None:
    if not isinstance(truth, dict) or set(truth) != {"state", "defects"}:
        raise GoldenTruthInvalid(f"{where}: truth must hold exactly state and defects")
    if truth["state"] not in STATES:
        raise GoldenTruthInvalid(f"{where}: unknown state {truth['state']!r}")
    defects = truth["defects"]
    if not isinstance(defects, list):
        raise GoldenTruthInvalid(f"{where}: defects must be a list")
    codes = []
    for defect in defects:
        if (not isinstance(defect, dict)
                or set(defect) != {"code", "severity", "required_refs"}
                or not isinstance(defect["code"], str)
                or defect["severity"] not in SEVERITIES
                or not isinstance(defect["required_refs"], list)
                or not all(isinstance(r, str) for r in defect["required_refs"])):
            raise GoldenTruthInvalid(f"{where}: malformed defect {defect!r}")
        codes.append(defect["code"])
    if len(set(codes)) != len(codes):
        raise GoldenTruthInvalid(f"{where}: duplicate defect code")
    if (truth["state"] == "FINDINGS") != bool(defects):
        raise GoldenTruthInvalid(f"{where}: state {truth['state']} disagrees with the defects")


def validate_document(name: str, document: Any) -> None:
    """Raise ``GoldenTruthInvalid`` unless the document is well formed and correctly sealed."""
    if not isinstance(document, dict) or document.get("schema") != SCHEMA:
        raise GoldenTruthInvalid(f"{name}: not a {SCHEMA} document")
    for field in ("set_id", "class_id", "description", "cases", DIGEST_FIELD):
        if field not in document:
            raise GoldenTruthInvalid(f"{name}: missing {field}")
    if document[DIGEST_FIELD] != seal(document):
        raise GoldenTruthInvalid(f"{name}: {DIGEST_FIELD} does not match the contents")
    cases = document["cases"]
    if not isinstance(cases, list) or not cases:
        raise GoldenTruthInvalid(f"{name}: no cases")
    seen = set()
    for index, case in enumerate(cases):
        where = f"{name} case {index}"
        needed = {"case_id", "capsule_commitment", "truth"}
        if not isinstance(case, dict) or not needed <= set(case):
            raise GoldenTruthInvalid(f"{where}: needs case_id, capsule_commitment, truth")
        commitment = case["capsule_commitment"]
        if not (isinstance(commitment, str) and commitment.startswith("sha256:")
                and len(commitment) == 71):
            raise GoldenTruthInvalid(f"{where}: malformed capsule_commitment")
        if case["case_id"] in seen:
            raise GoldenTruthInvalid(f"{where}: duplicate case_id {case['case_id']!r}")
        seen.add(case["case_id"])
        _check_truth(where, case["truth"])


class GoldenTruth:
    """Every published case, indexed by capsule evidence commitment."""

    def __init__(self, documents: dict[str, dict[str, Any]]) -> None:
        self.documents = documents
        self._by_commitment: dict[str, dict[str, Any]] = {}
        for name, document in documents.items():
            for case in document["cases"]:
                key, truth = case["capsule_commitment"], case["truth"]
                known = self._by_commitment.get(key)
                if known is not None and known != truth:
                    raise GoldenTruthInvalid(
                        f"{name}: capsule {key} has different truth in another file")
                self._by_commitment[key] = truth

    def __len__(self) -> int:
        return len(self._by_commitment)

    def truth_for(self, capsule: dict[str, Any]) -> dict[str, Any]:
        """The published truth of ``capsule``, bound by its recomputed evidence commitment."""
        key = evidence_commitment(capsule)
        truth = self._by_commitment.get(key)
        if truth is None:
            raise GoldenTruthMissing(
                f"no published truth for capsule {capsule.get('qid')!r} ({key})")
        return copy.deepcopy(truth)

    def digest(self) -> str:
        """One digest over the sealed files, in name order, for reports."""
        seals = [[name, self.documents[name][DIGEST_FIELD]] for name in sorted(self.documents)]
        return "sha256:" + hashlib.sha256(canonical_bytes(seals)).hexdigest()

    def describe(self) -> str:
        return (f"{len(self._by_commitment)} cases in {len(self.documents)} files under "
                f"protocol/golden_truth, digest {self.digest()}")


def load(directory: Path | None = None) -> GoldenTruth:
    """Read, validate and index every ``*.json`` file in the golden directory."""
    directory = GOLDEN_DIR if directory is None else directory
    paths = sorted(directory.glob("*.json")) if directory.is_dir() else []
    if not paths:
        raise GoldenTruthMissing(f"no golden truth files in {directory}")
    documents = {}
    for path in paths:
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as error:
            raise GoldenTruthInvalid(f"{path.name}: unreadable ({error})") from error
        validate_document(path.name, document)
        documents[path.name] = document
    return GoldenTruth(documents)


def main() -> int:
    try:
        store = load()
    except (GoldenTruthMissing, GoldenTruthInvalid) as error:
        print(f"GOLDEN TRUTH PROBLEM: {error}", file=sys.stderr)
        return 1
    print(store.describe())
    for name, document in sorted(store.documents.items()):
        print(f"  {name}: {document['set_id']} ({document['class_id']}), "
              f"{len(document['cases'])} cases, {document[DIGEST_FIELD]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
