#!/usr/bin/env python3
"""Render the testnet 582 uid / hotkey / method table from data, and check it has not drifted.

  uv run python scripts/render_uid_table.py          # print the table
  uv run python scripts/render_uid_table.py --check  # exit 1 if either README differs
  uv run python scripts/render_uid_table.py --write  # rewrite the marked block in both files

The table is built from ``attestation/TESTNET_582_PARTICIPANTS.json`` and cross-checked against
the attested weight rows in ``attestation/SN87_TESTNET_ATTESTATION_0{1,2}.json``: every attested
row must address exactly the uids the table names for the attested runs, and the "from block" of
those rows is read from the attestation, not typed. A value the data does not hold is shown as
"not recorded". Reads local files only; no network, no wallet.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARTICIPANTS = ROOT / "attestation" / "TESTNET_582_PARTICIPANTS.json"
ATTESTATIONS = [ROOT / "attestation" / f"SN87_TESTNET_ATTESTATION_0{n}.json" for n in (1, 2)]
TARGETS = [ROOT / "README.md", ROOT / "attestation" / "README.md"]
BEGIN = "<!-- BEGIN UID_TABLE -->"
END = "<!-- END UID_TABLE -->"
SCHEMA = "sn87.testnet_participants.v1"
FIRST_ATTESTED = "ATTESTATION_FIRST_INCLUDED_BLOCK"
NOT_RECORDED = "not recorded"


class TableError(ValueError):
    """The participant data and the attestation disagree, or a file is malformed."""


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def attested_rows() -> tuple[list[dict], int]:
    """Every attested weight row, and the lowest included block over them."""
    rows, blocks = [], []
    for path in ATTESTATIONS:
        for run in _load(path)["runs"]:
            rows.append(run["row"])
            blocks.append(run["included_block"])
    return rows, min(blocks)


def resolve(data: dict, first_attested: int) -> list[dict]:
    """Participant rows with the from block resolved, in uid then block order."""
    if data.get("schema") != SCHEMA:
        raise TableError(f"unexpected participants schema {data.get('schema')!r}")
    out = []
    for row in data["rows"]:
        period = data["periods"].get(row["period"]) if row["period"] else None
        block = period["from_block"] if period else None
        if block == FIRST_ATTESTED:
            block = first_attested
        out.append({**row, "from_block": block, "applies": period["label"] if period else None,
                    "basis": period["basis"] if period else None})
    return sorted(out, key=lambda r: (r["uid"], r["from_block"] or 0))


def cross_check(data: dict, rows: list[dict]) -> None:
    """The attested rows must address exactly the uids the table names for the attested runs."""
    for path in ATTESTATIONS:
        attestation = _load(path)
        for field in ("netuid", "mecid", "validator_uid"):
            if attestation[field] != data[field]:
                raise TableError(f"{field} {data[field]!r} differs from {path.name} "
                                 f"({attestation[field]!r})")
    label = data["periods"]["attested_runs"]["label"]
    named = sorted(r["uid"] for r in rows if r["applies"] == label)
    for row in attested_rows()[0]:
        if sorted(row["dests"]) != named:
            raise TableError(f"attested row dests {row['dests']} differ from table uids {named}")
        if len(set(row["weights"])) != 1:
            raise TableError("attested weights are not equal; the table notes assume a tie")
    keys = {(r["uid"], r["hotkey"]) for r in rows if r["uid"] in named}
    if len({uid for uid, _ in keys}) != len(keys):
        raise TableError("a uid is shown with more than one hotkey")
    if data["validator_uid"] not in {r["uid"] for r in rows if r["role"] == "validator"}:
        raise TableError("the validator uid has no validator row")


def render(data: dict | None = None) -> str:
    data = _load(PARTICIPANTS) if data is None else data
    first_attested = attested_rows()[1]
    rows = resolve(data, first_attested)
    cross_check(data, rows)
    lines = [f"Testnet netuid {data['netuid']}, mechanism {data['mecid']}. Generated by "
             "`scripts/render_uid_table.py` from `attestation/TESTNET_582_PARTICIPANTS.json`; "
             "`--check` fails if this table drifts from that file or from the attestation.", "",
             "| uid | hotkey | method | role | from block | weight row | basis for the method |",
             "| --- | --- | --- | --- | --- | --- | --- |"]
    for r in rows:
        block = f"{r['from_block']:,}" if r["from_block"] is not None else NOT_RECORDED
        lines.append(f"| {r['uid']} | `{r['hotkey']}` | "
                     f"{('`' + r['method'] + '`') if r['method'] else 'none (validator)'} | "
                     f"{r['role']} | {block} | {r['applies'] or 'not applicable'} | "
                     f"{r['basis'] or 'not applicable'} |")
    lines += ["", *[f"- {note}" for note in data["notes"]]]
    lines += [f"- `{m}`: {text}" for m, text in data["method_notes"].items()]
    return "\n".join(lines) + "\n"


def splice(text: str, table: str) -> str:
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise TableError("expected exactly one UID_TABLE marker pair")
    head, rest = text.split(BEGIN + "\n", 1)
    _, tail = rest.split(END, 1)
    return head + BEGIN + "\n" + table + END + tail


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    try:
        table = render()
        if not (args.check or args.write):
            print(table, end="")
            return 0
        drifted = []
        for path in TARGETS:
            current = path.read_text(encoding="utf-8")
            wanted = splice(current, table)
            if wanted != current:
                drifted.append(path.relative_to(ROOT).as_posix() if path.is_relative_to(ROOT)
                               else path.name)
                if args.write:
                    path.write_text(wanted, encoding="utf-8")
    except (TableError, OSError, KeyError, ValueError) as error:
        print(f"uid table: {error}", file=sys.stderr)
        return 1
    if drifted and args.check:
        print("uid table drifted in: " + ", ".join(drifted), file=sys.stderr)
        return 1
    print("uid table:", "rewritten " + ", ".join(drifted) if drifted else "up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
